### ISSUE TITLE
Incorrect handling of PDOException

### ISSUE THREAD

**Issue by gms8994** [austinkregel/php-exception-probe#3]
This example of an exception coming directly from a live application - the PDOException has the PDO error first, which causes an error on https://github.com/austinkregel/php-exception-probe/blob/master/src/Stacktrace.php#L140, because the regex doesn't match. 

```
$stack = new Kregel\ExceptionProbe\Stacktrace(); 
$stack->parse(<<<EOF
PDOException: SQLSTATE[22008]: Datetime field overflow: 7 ERROR:  date/time field value out of range: "1967-12-0"
HINT:  Perhaps you need a different "datestyle" setting. in /var/www/releases/20181217174644/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:142
Stack trace:
#0 /var/www/releases/20181217174644/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php(142): PDOStatement->execute(NULL)
#1 /var/www/releases/20181217174644/vendor/laravel/framework/src/Illuminate/Database/Connection.php(330): Doctrine\DBAL\Driver\PDOStatement->execute()
#2 /var/www/releases/20181217174644/vendor/laravel/framework/src/Illuminate/Database/Connection.php(657): Illuminate\Database\Connection->Illuminate\Database\{closure}('insert into "Dm...', Array)
EOF
);
```

**Comment by austinkregel** [comment]
Oh interesting 🤔 I'll look into adding this 😄 Thanks for reporting it!

**Comment by gms8994** [comment]
I had planned to make a PR for this yesterday when I wrote up the issue, but didn't have a chance. Please see and review the mentioned PR.

**Comment by austinkregel** [comment]
I'll review it once I get off of work 😄 thanks for submitting the PR!

**Comment by austinkregel** [comment]
Sorry about this 😅 Normally I don't take this long to review code. I'll be able to review it again (with the suggested changes) over the next day or two.

**Comment by austinkregel** [comment]
I just wanted you to know @gms8994 that this will be marked and released within an hour.
